### ISSUE TITLE
老哥更新一下文章啊,等着看解决方案三呢

### ISSUE THREAD

**Issue by kpas8288** [Meano/RG200O-SwitchAdmin#1]
都两年了
https://www.meano.net/Blog/04/342

**Comment by Meano** [comment]
哈哈 Sorry，没想到真有人能看到这篇文章。

目前已经用HG8240T代替了RG200O，简单说下思路修改思路，可能并不准确了仅供参考。

研究固件内的文件发现不同地区的配置在 /etc/cu/* 下，其中的 soft_feature.cfg 应该是针对不同地区的配置，其中有一项为 support_bjcu_admin 此项应该是导致 cu.html 被重定向的源头。

修改此项可以用两种办法：

1. Shell 命令中有 soft_feature 命令，可以用来临时修改此配置，重启后会失效。
2. 可以直接光猫区域配置文件 soft_feature.cfg。由于Root区是 RO 的，所以修改 /etc/cu/*/soft_feature.cfg 文件 (*代表区域配置，比如北京EPON对应asb-beijing-epon-h248) 需要用一些特殊的手段，我可能用了 mount –bind 覆盖了文件，或者是重新写入了squashfs。

**Comment by Meano** [comment]
另外勘误：启用Telnet的那个地址也是回忆写的，不准确，后来整理了原文件发现应该是 bjcfg.html 。

**Comment by kpas8288** [comment]
谢谢
我参考一下
